In [43]:
from pathlib import Path
import pandas as pd
import json

In [6]:
scopus_result_path = Path("scopus_results/included_results.csv")
df = pd.read_csv(scopus_result_path)
df.to_clipboard()

,id,project_id,probability,pmid,refman,title,abstract,authors,journal,volume,...,filename,resolution_labels,resolution_labels_alternate,labels,labels_alternate,tags,general,population,intervention_comparator,outcome
0,4290040,3614,0,NaN,NaN,Quantum kernel estimation-based quantum suppor...,Quantum machine learning endeavors to exploit ...,"Zhou, Xiaojian (55743236400); Yu, Jieyao (5798...",Quantum Information Processing,23,...,scopus_export_Mar 13-2026_bd893968-dc41-4186-9...,NaN,NaN,1,yes,NaN,NaN,NaN,NaN,NaN
1,4290037,3614,0,NaN,NaN,QAISim: a toolkit for modeling and simulation ...,Quantum computing offers new ways to explore t...,"Singh, Irwindeep (60286751400); Gill, Sukhpal ...",Cluster Computing,29,...,scopus_export_Mar 13-2026_bd893968-dc41-4186-9...,NaN,NaN,1,yes,NaN,NaN,NaN,NaN,NaN
2,4290036,3614,0,NaN,NaN,Quantum-Based QoE Optimization in Advanced Cel...,This work explores the integration of Quantum ...,"Chaouech, Fatma (60057005200); Villegas, Javie...",IEEE Open Journal of the Communications Society,6,...,scopus_export_Mar 13-2026_bd893968-dc41-4186-9...,NaN,NaN,1,yes,NaN,NaN,NaN,NaN,NaN
3,4290035,3614,0,NaN,NaN,Parallel hybrid quantum-classical machine lear...,Supervised time-series classification garners ...,"Baker, Jack S. (57462192800); Park, Gilchan (5...",Quantum Machine Intelligence,6,...,scopus_export_Mar 13-2026_bd893968-dc41-4186-9...,NaN,NaN,1,yes,NaN,NaN,NaN,NaN,NaN
4,4290032,3614,0,NaN,NaN,Quantum-Enhanced Dual-Backbone Architecture fo...,Background: Quantum machine learning (QML) hol...,"Marzoug, Nabil (58817844100); Halab, Khidhr (5...",BioMedInformatics,5,...,scopus_export_Mar 13-2026_bd893968-dc41-4186-9...,NaN,NaN,1,yes,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,4289594,3614,0,NaN,NaN,Quantum generative learning for high-resolutio...,Integration of quantum computing in generative...,"Khatun, Amena (57212796083); Yeter Aydeniz, Kü...",Machine Learning: Science and Technology,6,...,scopus_export_Mar 13-2026_bd893968-dc41-4186-9...,NaN,NaN,1,yes,NaN,NaN,NaN,NaN,NaN
196,4289593,3614,0,NaN,NaN,Development of variational quantum deep neural...,Parametrized quantum circuits are widely used ...,"Wang, Yunqian (57201779541); Wang, Yufeng (577...",Neurocomputing,501,...,scopus_export_Mar 13-2026_bd893968-dc41-4186-9...,NaN,NaN,1,yes,NaN,NaN,NaN,NaN,NaN
197,4289592,3614,0,NaN,NaN,New perspectives on structural health monitori...,This study presents a novel approach using uns...,"Higino Meneguitte Alves, Victor (59644697100);...",Mechanical Systems and Signal Processing,229,...,scopus_export_Mar 13-2026_bd893968-dc41-4186-9...,NaN,NaN,1,yes,NaN,NaN,NaN,NaN,NaN
198,4289591,3614,0,NaN,NaN,Quantum enhanced stratification of breast canc...,Quantum machine learning (QML) is considered o...,"Repetto, Valeria (57224996797); Ceroni, Elia G...",Quantum Machine Intelligence,7,...,scopus_export_Mar 13-2026_bd893968-dc41-4186-9...,NaN,NaN,1,yes,NaN,NaN,NaN,NaN,NaN
199,4289590,3614,0,NaN,NaN,Quantum extreme learning of molecular potentia...,Quantum machine learning algorithms are expect...,"Lo Monaco, Gabriele (57203892387); Bertini, Ma...",Machine Learning: Science and Technology,5,...,scopus_export_Mar 13-2026_bd893968-dc41-4186-9...,NaN,NaN,1,yes,NaN,NaN,NaN,NaN,NaN

In [31]:
from random import randint

indexes = []
while len(set(indexes)) < 20:
	indexes = [randint(0, 199) for i in range(1, 21)]
selected_abstracts = df.iloc[indexes]

In [32]:
selected_abstracts[["id", "abstract"]]

          id                                           abstract
9    4290026  Ensuring the safety, reliability, and longevit...
175  4289647  Quantum neural networks have emerged as a prom...
30   4289991  Quantum machine learning (QML) is a method for...
69   4289914  Skin diseases affect millions of people worldw...
96   4289850  The emerging paradigm of quantum machine learn...
144  4289744  Quantum machine learning is a relatively new r...
135  4289770  Quantum computing, with its unique principles ...
70   4289912  Electroencephalography (EEG) is widely used in...
115  4289813  Quantum Machine Learning represents a promisin...
156  4289718  Image classification has an important role in ...
21   4290008  The perovskite materials with the chemical str...
163  4289686  Credit cards are a common form of payment not ...
165  4289683  Quantum machine learning (QML) is an emerging ...
8    4290028  With the rapid advance of quantum machine lear...
109  4289821  We provide a robust defence to adversarial att...
164  4289684  The application of quantum machine learning to...
68   4289918  Forecasting commodity prices is challenging du...
19   4290011  In this paper, electrical discharge images are...
0    4290040  Quantum machine learning endeavors to exploit ...
1    4290037  Quantum computing offers new ways to explore t...

In [120]:
keywords = {
	4290026: {
		"domain": ["Intelligent Transportation Systems", "anomaly detection"],
		"models": ["Variational Quantum Neural Network"]
	},
	4289647: {
		"domain": ["image classification"],
		"models": ["Hybrid quantum-neural network"]
	},
	4289991: {
		"domain": ["Healthcare", "diagnosis", "treatment"],
		"models": ["Quantum Variational Classifier", "Parameterized Quantum Circuits"]
	},
	4289914: {
		"domain": ["Healthcare", "Skin diseases", "diagnosis"],
		"models": ["Quanvolutional neural network", "Quantum Support Vector Classifier"]
	},
	4289850: {
		"domain": ["Network traffic detection", "anomaly detection", "cybersecurity"],
		"models": ["quantum convolutional neural network"]
	},
	4289744: {
		"domain": ["chemistry", "atomization energies"],
		"models": ["quantum linear regression", "quantum radial basis function neural network",
				   "quantum neural network"]
	},
	4289770: {
		"domain": ["text classification"],
		"models": ["Complex Quantum Kernel Self-Attention Network"]
	},
	4289912: {
		"domain": ["healthcare", "electroencephalography classification"],
		"models": ["Quantum-EEGNet", "hybrid quantum-neural network"]
	},
	4289813: {
		"domain": ["healthcare", "classification of cardiovascular disease"],
		"models": ["hybrid quantum-neural network"]
	},
	4289718: {
		"domain": ["image classification"],
		"models": ["quanvolutional neural network"]
	},
	4290008: {
		"domain": ["chemistry", "lattice constants"],
		"models": ["Quantum Support Vector Regression"]
	},
	4289686: {
		"domain": ["Credit card fraud detection", "Fraud detection"],
		"models": ["Not specified"]
	},
	4289683: {
		"domain": ["healthcare", "electroencephalogram classification"],
		"models": ["quantum support vector machine"]
	},
	4290028: {
		"domain": ["image classification"],
		"models": ["quantum convolutional neural networks"]
	},
	4289821: {
		"domain": ["Not specified"],
		"models": ["Not specified"]
	},
	4289684: {
		"domain": ["High-resolution image classification"],
		"models": ["quantum transfer learning", "quantum variational circuits"]
	},
	4289918: {
		"domain": ["Finance", "Price forcasting", "time-series data"],
		"models": ["Quantum Long Short-Term Memory"]
	},
	4290011: {
		"domain": ["electrical discharge classification"],
		"models": ["quantum variational model", "quantum support vector machine"]
	},
	4290040: {
		"domain": ["Not specified"],
		"models": ["quantum support vector machine",
				   "quantum kernel estimation-based quantum support vector regression"]
	},
	4290037: {
		"domain": ["resource allocation"],
		"models": ["quantum reinforcement learning", "parameterized quantum circuits"]
	}
}
keywords_df = pd.DataFrame([
	{"id": k, "domains": v["domain"], "models": v["models"]}
	for k, v in keywords.items()
])
selected_abstracts = selected_abstracts.merge(keywords_df, on="id", how="left")
selected_abstracts

,id,project_id,probability,pmid,refman,title,abstract,authors,journal,volume,...,resolution_labels_alternate,labels,labels_alternate,tags,general,population,intervention_comparator,outcome,domains,models
0,4290026,3614,0,NaN,NaN,Quantum-Enhanced Battery Anomaly Detection in ...,"Ensuring the safety, reliability, and longevit...","Mutua, Alexander Mutiso (58950221200); de Fréi...",Applied Sciences (Switzerland),15,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[Intelligent Transportation Systems, anomaly d...",[Variational Quantum Neural Network]
1,4289647,3614,0,NaN,NaN,LHQNN: sequential and non-sequential layered h...,Quantum neural networks have emerged as a prom...,"Kabir, Monika (57208737420); Kaosar, Mohammed ...",Quantum Machine Intelligence,7,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,[image classification],[Hybrid quantum-neural network]
2,4289991,3614,0,NaN,NaN,Enhanced deep learning and quantum variational...,Quantum machine learning (QML) is a method for...,"D, Sudha (59299201900); A, Anju (57415753800);...",Knowledge-Based Systems,330,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[Healthcare, diagnosis, treatment]","[Quantum Variational Classifier, Parameterized..."
3,4289914,3614,0,NaN,NaN,Exploring Quantum Machine Learning for Enhance...,Skin diseases affect millions of people worldw...,"Reka, S. Sofana (56964480300); Karthikeyan, H....",IEEE Access,12,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[Healthcare, Skin diseases, diagnosis]","[Quanvolutional neural network, Quantum Suppor..."
4,4289850,3614,0,NaN,NaN,Network attack traffic detection with hybrid q...,The emerging paradigm of quantum machine learn...,"Wang, Zihao (57354050700); Fok, Kar Wai (57353...",Quantum Machine Intelligence,7,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[Network traffic detection, anomaly detection,...",[quantum convolutional neural network]
5,4289744,3614,0,NaN,NaN,A hybrid quantum regression model for the pred...,Quantum machine learning is a relatively new r...,"Reddy, Pranath (57219506972); Bhattacherjee, A...",Machine Learning: Science and Technology,2,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[chemistry, atomization energies]","[quantum linear regression, quantum radial bas..."
6,4289770,3614,0,NaN,NaN,Enhancing Text Classification Through Quantum ...,"Quantum computing, with its unique principles ...","Chen, Xiaoxiao (57203434933); Lou, Xiaoping (5...",IEEE Access,13,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,[text classification],[Complex Quantum Kernel Self-Attention Network]
7,4289912,3614,0,NaN,NaN,Exploring the Potential of QEEGNet for Cross-t...,Electroencephalography (EEG) is widely used in...,"Chen, Chi-Sheng (57850710600); Chen, Samuel Ye...",Journal of Signal Processing Systems,98,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[healthcare, electroencephalography classifica...","[Quantum-EEGNet, hybrid quantum-neural network]"
8,4289813,3614,0,NaN,NaN,A hybrid quantum-neural network for heart dise...,Quantum Machine Learning represents a promisin...,"Verdone, Alessio (57943904400); Succetti, Fede...",Biomedical Signal Processing and Control,113,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[healthcare, classification of cardiovascular ...",[hybrid quantum-neural network]
9,4289718,3614,0,NaN,NaN,Exploring the features of quanvolutional neura...,Image classification has an important role in ...,"Vu, Tuan Hai (57226005510); Le, Lawrence H. (7...",Quantum Machine Intelligence,6,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,[image classification],[quanvolutional neural network]
10,4290008,3614,0,NaN,NaN,Predicting lattice constant in ABX3 perovskite...,The perovskite materials with the chemical str...,"Akrom, Muhamad (58054974800); Rustad, Supriadi...",Computational Materials Science,253,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[chemistry, lattice constants]",[Quantum Support Vector Regression]
11,4289686,3614,0,NaN,NaN,Toward Efficient Credit Card Fraud Detection: ...,Credit cards are a common form of payment not ...,"Deepa, N. (57209685004); Jayaraj, R. (57215271...",Journal of Machine and Computing,5,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[Credit card fraud detection, Fraud detection]",[Not specified]
12,4289683,3614,0,NaN,NaN,A Quantum Mechanics-Based Framework for EEG Si...,Quantum machine learning (QML) is an emerging ...,"Li, YaoChong (57208259132); Zhou, Ri-Gui (2293...",IEEE Transactions on Emerging Topics in Computing,10,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[healthcare, electroencephalogram classification]",[quantum support vector machine]
13,4290028,3614,0,NaN,NaN,Quantum convolutional neural network for class...,With the rapid advance of quantum machine lear...,"Hur, Tak (57226888332); Kim, Leeseok (57226892...",Quantum Machine Intelligence,4,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,[image classification],[quantum convolutional neural networks]
14,4289821,3614,0,NaN,NaN,Defence against adversarial attacks using clas...,We provide a robust defence to adversarial att...,"Kehoe, Aidan (57221917391); Wittek, Peter (351...",Machine Learning: Science and Technology,2,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,[Not specified],[Not specified]
15,4289684,3614,0,NaN,NaN,Quantum Transfer Learning with Adversarial Rob...,The application of quantum machine learning to...,"Khatun, Amena (57212796083); Usman, Muhammad (...",Advanced Quantum Technologies,8,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,[High-resolution image classification],"[quantum transfer learning, quantum variationa..."
16,4289918,3614,0,NaN,NaN,A study on a hybrid autoencoder–QLSTM model fo...,Forecasting commodity prices is challenging du...,"Jang, Haiwon (60411967500); Yang, Seungryeol (...",Quantum Machine Intelligence,8,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,"[Finance, Price forcasting, time-series data]",[Quantum Long Short-Term Memory]
17,4290011,3614,0,40006505.0,NaN,Quantum Variational vs. Quantum Kernel Machine...,"In this paper, electrical discharge images are...","Monzón-Verona, José Miguel (26531597500); Garc...",Sensors,25,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,[electrical discharge classification],"[quantum variational model, quantum support ve..."
18,4290040,3614,0,NaN,NaN,Quantum kernel estimation-based quantum suppor...,Quantum machine learning endeavors to exploit ...,"Zhou, Xiaojian (55743236400); Yu, Jieyao (5798...",Quantum Information Processing,23,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,[Not specified],"[quantum support vector machine, quantum kerne..."
19,4290037,3614,0,NaN,NaN,QAISim: a toolkit for modeling and simulation ...,Quantum computing offers new ways to explore t...,"Singh, Irwindeep (60286751400); Gill, Sukhpal ...",Cluster Computing,29,...,NaN,1,yes,NaN,NaN,NaN,NaN,NaN,[resource allocation],"[quantum reinforcement learning, parameterized..."

In [ ]:
selected_abstracts.drop(columns=["domains_x", "domains_y", "models_x", "models_y"], inplace=True)
selected_abstracts

In [121]:
def parse_json(text):
	try:
		return json.loads(text)
	except:
		return {"domains": [], "models": []}

In [122]:
llm_keywords = pd.read_csv("results/extracted_keywords.csv")
parsed_dicts = llm_keywords['extracted_data'].apply(parse_json)
expanded_df = pd.json_normalize(parsed_dicts)
llm_keywords = pd.concat([llm_keywords.drop(columns=['extracted_data']), expanded_df], axis=1)
llm_keywords.rename(columns={"domains": "llm_suggested_domains", "models": "llm_suggested_models", "doi": "id"},
					inplace=True)
llm_keywords

,original_index,id,llm_suggested_domains,llm_suggested_models
0,0,4290040,[Not Specified],"[Quantum Support Vector Machine, Quantum Suppo..."
1,1,4290037,"[Internet of Things, Cloud Computing]","[Parameterized Quantum Circuit, Quantum Reinfo..."
2,2,4290036,"[Telecommunications, Cloud Gaming]","[Quantum Machine Learning, Quantum-Inspired]"
3,3,4290035,"[Finance, Astronomy, Biosensors]","[QCC-net, time-series Hamiltonian kernel]"
4,4,4290032,[Healthcare],[Fused Quantum Dual-Backbone Network]
...,...,...,...,...
195,195,4289594,[Healthcare],"[Quantum Generative Adversarial Networks, Quan..."
196,196,4289593,[Image Recognition],[Variational quantum deep neural network]
197,197,4289592,"[Structural Health Monitoring, Civil Engineering]",[Quantum classifier]
198,198,4289591,"[Medicine, Biology, Oncology]",[Quantum kernels]
199,199,4289590,[Quantum Chemistry],"[Quantum Neural Network, Quantum Extreme Learn..."

In [123]:
merged_df = llm_keywords.merge(keywords_df, on="id", how="inner")
merged_df

,original_index,id,llm_suggested_domains,llm_suggested_models,domains,models
0,0,4290040,[Not Specified],"[Quantum Support Vector Machine, Quantum Suppo...",[Not specified],"[quantum support vector machine, quantum kerne..."
1,1,4290037,"[Internet of Things, Cloud Computing]","[Parameterized Quantum Circuit, Quantum Reinfo...",[resource allocation],"[quantum reinforcement learning, parameterized..."
2,8,4290028,[Not Specified],"[Quantum convolutional neural networks, Quantu...",[image classification],[quantum convolutional neural networks]
3,9,4290026,"[Electric Vehicles, Intelligent Transportation...","[Variational Quantum Neural Network, Quantum A...","[Intelligent Transportation Systems, anomaly d...",[Variational Quantum Neural Network]
4,19,4290011,[Electrical Engineering],"[quantum variational model, quantum kernel model]",[electrical discharge classification],"[quantum variational model, quantum support ve..."
5,21,4290008,"[Optoelectronics, Solar cells, Catalysis, Mate...",[Quantum Support Vector Regression],"[chemistry, lattice constants]",[Quantum Support Vector Regression]
6,30,4289991,[Healthcare],"[Quantum Variational Classifier, Parameterized...","[Healthcare, diagnosis, treatment]","[Quantum Variational Classifier, Parameterized..."
7,68,4289918,[Finance],[Quantum Long Short-Term Memory],"[Finance, Price forcasting, time-series data]",[Quantum Long Short-Term Memory]
8,69,4289914,[Healthcare],"[Quanvolutional neural network, Quantum suppor...","[Healthcare, Skin diseases, diagnosis]","[Quanvolutional neural network, Quantum Suppor..."
9,70,4289912,"[Neuroscience, Clinical Research]",[Quantum-EEGNet],"[healthcare, electroencephalography classifica...","[Quantum-EEGNet, hybrid quantum-neural network]"
10,96,4289850,"[Cybersecurity, Network Traffic Analysis]",[Quantum Convolutional Neural Network],"[Network traffic detection, anomaly detection,...",[quantum convolutional neural network]
11,109,4289821,[Not Specified],[Boltzmann machines],[Not specified],[Not specified]
12,115,4289813,[Healthcare],"[Hybrid Quantum-Neural Network, Quantum Neural...","[healthcare, classification of cardiovascular ...",[hybrid quantum-neural network]
13,135,4289770,"[Artificial Intelligence, Natural Language Pro...",[Complex Quantum Kernel Self-Attention Network],[text classification],[Complex Quantum Kernel Self-Attention Network]
14,144,4289744,[Chemistry],"[quantum linear regression, quantum radial bas...","[chemistry, atomization energies]","[quantum linear regression, quantum radial bas..."
15,156,4289718,[Image processing],[quanvolutional neural network],[image classification],[quanvolutional neural network]
16,163,4289686,[Finance],[Not Specified],"[Credit card fraud detection, Fraud detection]",[Not specified]
17,164,4289684,"[Computer Vision, Transportation]","[quantum variational circuits, quantum transfe...",[High-resolution image classification],"[quantum transfer learning, quantum variationa..."
18,165,4289683,[Healthcare],[Quantum Support Vector Machine],"[healthcare, electroencephalogram classification]",[quantum support vector machine]
19,175,4289647,[Image Classification],"[Quantum Neural Network, Hybrid Quantum Neural...",[image classification],[Hybrid quantum-neural network]

In [126]:
scores = {
	4290040: [1, 1],
	4290037: [0, 1],
	4290028: [1, 1],
	4290026: [1, 1],
	4290011: [1, 1],
	4290008: [1, 1],
	4289991: [1, 1],
	4289918: [1, 1],
	4289914: [1, 1],
	4289912: [1, 1],
	4289850: [1, 1],
	4289821: [1, 0],
	4289813: [1, 1],
	4289770: [1, 1],
	4289744: [1, 1],
	4289718: [1, 1],
	4289686: [1, 1],
	4289684: [1, 1],
	4289683: [1, 1],
	4289647: [1, 1],
}
scores_df = pd.DataFrame([{"id": k, "domain_score": v[0], "model_score": v[1]} for k, v in scores.items()])
merged_df = merged_df.merge(scores_df, on="id", how="left")

domain_agreement = merged_df["domain_score"].sum() / len(merged_df["domain_score"])
model_agreement = merged_df["model_score"].sum() / len(merged_df["model_score"])

print(f"Domain agreement rate: {domain_agreement:.2%}")
print(f"Model agreement rate: {model_agreement:.2%}")

Domain agreement rate: 95.00%
Model agreement rate: 95.00%

In [128]:
merged_df.to_csv("results\piloted_results.csv")